services:
  web:
    build:
      context: "./docker/web/"
    container_name: web
    volumes:
      - ./:/var/www/
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
